from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.dashboard,
        name='dashboard'
    ),
    path(
        'manage_faq/',
        views.manage_faq,
        name='manage_faq'
    ),
    path(
        'manage_faq/<int:faq_id>/',
        views.manage_faq,
        name='manage_faq'
    ),
    path(
        'manage_faq/<str:delete>/<int:faq_id>/',
        views.manage_faq, name='manage_faq'
    ),
    path(
        'manage_faq_topic/',
        views.manage_faq_topic,
        name='manage_faq_topic'
    ),
    path(
        'manage_faq_topic/<int:faq_topic_id>/',
        views.manage_faq_topic,
        name='manage_faq_topic'
    ),
    path(
        'manage_faq_topic/<str:delete>/<int:faq_topic_id>/',
        views.manage_faq_topic,
        name='manage_faq_topic'
    ),
    path('manage_product/',
         views.manage_product,
         name='manage_product'),
    path(
        'manage_product/<int:product_id>/',
        views.manage_product,
        name='manage_product'
    ),
    path(
        'manage_product/<str:delete>/<int:product_id>/',
        views.manage_product,
        name='manage_product'
    ),
    path(
        'reply_to_message/<int:message_id>/',
        views.reply_to_message,
        name='reply_to_message'
    ),
    path(
        'manage_subscriber/<int:subscriber_id>/',
        views.manage_subscriber,
        name='manage_subscriber'
    ),
    path(
        'clear_expired/',
        views.clear_expired_subscribers,
        name='clear_expired_subscribers'
    ),
    path(
        'manage_newsletters/',
        views.manage_newsletters,
        name='manage_newsletters'
    ),
    path(
        'manage_newsletters/<int:newsletter_id>/',
        views.manage_newsletters,
        name='manage_newsletters'
    ),
    path(
        'manage_newsletters/<str:delete>/<int:newsletter_id>/',
        views.manage_newsletters,
        name='manage_newsletters'
    ),
]
