# Generated by Django 5.1.4 on 2025-02-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqsTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faqs',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.faqstopics'),
        ),
    ]
