# Generated by Django 5.1.4 on 2025-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_faqstopics_alter_faqs_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='faqstopics',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'FAQ Topics'},
        ),
        migrations.AddField(
            model_name='faqstopics',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
