# Generated by Django 5.1.4 on 2025-02-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_faqs_options_faqs_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['topic', 'sort_order'], 'verbose_name_plural': 'FAQs'},
        ),
    ]
