# Generated by Django 5.1.4 on 2025-02-12 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_faqs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date_received',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_replied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqstopics',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
