# Generated by Django 5.1.4 on 2025-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_contactmessage_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['replied']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_number',
            field=models.CharField(default='DEFAULT', max_length=32),
            preserve_default=False,
        ),
    ]
