# Generated by Django 5.1.4 on 2025-02-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['date_sent']},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='date_joined',
            new_name='date_sent',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='news_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='sub', max_length=254),
            preserve_default=False,
        ),
    ]
