# Generated by Django 5.1.4 on 2025-02-13 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_subscriber_is_active_subscriber_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
