# Generated by Django 5.1.4 on 2025-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_subscriber_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
