# Generated by Django 5.1.4 on 2025-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
