# Generated by Django 5.1.4 on 2025-03-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_alter_subscriber_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_topic', to='support.faqstopics'),
        ),
    ]
