# Generated by Django 5.1.4 on 2025-03-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_alter_faqs_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-date_sent']},
        ),
    ]
