# Generated by Django 5.1.4 on 2025-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faqstopics',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
