# Generated by Django 5.1.4 on 2025-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_alter_faqs_question_alter_faqstopics_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
