# Generated by Django 5.1.4 on 2025-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_alter_contactmessage_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqstopics',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'FAQ Topics'},
        ),
    ]
