# Generated by Django 5.1.4 on 2025-02-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
