# Generated by Django 5.1.4 on 2025-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rewards_used',
            field=models.TextField(default=''),
        ),
    ]
