# Generated by Django 5.1.4 on 2025-02-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_rewards_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rewards_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
