# Generated by Django 5.1.4 on 2025-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_rewards_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
