# Generated by Django 5.1.4 on 2025-02-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orderlineitem_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='original_price',
            new_name='adjusted_price',
        ),
    ]
