# Generated by Django 5.1.4 on 2025-02-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_rename_original_price_orderlineitem_adjusted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='adjusted_price',
            new_name='purchase_price',
        ),
    ]
