# Generated by Django 5.1.4 on 2025-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='the_prefix_required',
            field=models.BooleanField(default=False),
        ),
    ]
