# Generated by Django 5.1.4 on 2025-02-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_local_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='local_image',
        ),
    ]
