# Generated by Django 5.1.4 on 2025-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_local_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True),
        ),
    ]
