# Generated by Django 5.1.4 on 2025-02-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['realm__name']},
        ),
    ]
