# Generated by Django 5.1.4 on 2025-03-13 11:41

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_realm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [django.db.models.functions.text.Lower('realm__name')]},
        ),
    ]
