# Generated by Django 5.1.4 on 2025-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
