# Generated by Django 5.1.4 on 2025-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='name',
            field=models.CharField(help_text='TEST', max_length=254, unique=True),
        ),
    ]
